env:
  WAYPOINT_SERVER_TOKEN: bM152PWkXxfoy4vA51JFhR7LoCDtMFhBgvRewMJ4sZvbft1KE7mEoZBRQqYvRC9RZCnmBsmGk2MopuNoEs179VLKcSNiGWvRvDN6k
  WAYPOINT_SERVER_ADDR: waypoint.example.com:9701
  WAYPOINT_SERVER_TLS: 1
  WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1

steps:
  - uses: actions/checkout@v2
  - uses: hashicorp/action-setup-waypoint
    with:
      version: '0.1.0'
- run: waypoint init
- run: waypoint build
